main: me.phantomclone.minewars.buildserversystem.BuildServerPluginImpl
name: BuildServerSystem
api-version: 1.19
version: 1.0
commands:
  buildsystem:
    permission: 'buildsystem.builder'
    description: 'Open main gui'
  gamemode:
    permission: 'buildsystem.builder'
    description: 'Change your gamemode'
    aliases:
      - 0
      - 1
      - 2
      - gm
    usage: 'use /gamemode <0|1|2>'